proxies:
- name: åŠ æ‹¿å¤§ 001 @schpd
  type: vmess
  server: t1.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.620720.xyz
- name: åŠ æ‹¿å¤§ 002 @schpd
  type: vmess
  server: 15.235.41.200
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 003 @schpd
  type: vmess
  server: 104.17.18.26
  port: 80
  uuid: 5180444a-4756-43b4-960b-49eb9052e4e8
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 004 @schpd
  type: vmess
  server: 104.21.75.246
  port: 80
  uuid: c458695d-6908-45c3-9512-e0c46418454c
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 005 @schpd
  type: vmess
  server: 51.79.102.253
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 006 @schpd
  type: vmess
  server: 104.26.8.44
  port: 80
  uuid: 5180444a-4756-43b4-960b-49eb9052e4e8
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 007 @schpd
  type: vmess
  server: sy4.620720.xyz
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sy4.620720.xyz
- name: åŠ æ‹¿å¤§ 008 @schpd
  type: vmess
  server: hgtrojan.zabc.net
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /e6395c20
    headers:
      Host: hgtrojan.zabc.net
- name: å¢¨è¥¿å“¥ 009 @schpd
  type: vmess
  server: 216.238.87.47
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: none
- name: ç¾Žå›½ 010 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: ç¾Žå›½ 011 @schpd
  type: vmess
  server: cg1c14.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c14.waimaojd.com
- name: ç¾Žå›½ 012 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: ç¾Žå›½ 013 @schpd
  type: vmess
  server: 209.126.84.189
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /vmessws
    headers:
      Host: 209.126.84.189
- name: ç¾Žå›½ 014 @schpd
  type: vmess
  server: cg1c04.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c04.waimaojd.com
- name: ç¾Žå›½ 015 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: ç¾Žå›½ 016 @schpd
  type: vmess
  server: support.zoom.us
  port: 8080
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /@Malinda6104
    headers:
      Host: support.zoom.us
- name: ç¾Žå›½ 017 @schpd
  type: vmess
  server: cg1c01.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c01.waimaojd.com
- name: ç¾Žå›½ 018 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: ç¾Žå›½ 019 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: ç¾Žå›½ 020 @schpd
  type: vmess
  server: cg1c07.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c07.waimaojd.com
- name: ç¾Žå›½ 021 @schpd
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 022 @schpd
  type: vmess
  server: v35.hdacd.com
  port: 30835
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 023 @schpd
  type: vmess
  server: v10.hdacd.com
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 024 @schpd
  type: vmess
  server: v36.hdacd.com
  port: 30836
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 025 @schpd
  type: vmess
  server: v10.hdacd.com
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - åŠ æ‹¿å¤§ 001 @schpd
  - åŠ æ‹¿å¤§ 002 @schpd
  - åŠ æ‹¿å¤§ 003 @schpd
  - åŠ æ‹¿å¤§ 004 @schpd
  - åŠ æ‹¿å¤§ 005 @schpd
  - åŠ æ‹¿å¤§ 006 @schpd
  - åŠ æ‹¿å¤§ 007 @schpd
  - åŠ æ‹¿å¤§ 008 @schpd
  - å¢¨è¥¿å“¥ 009 @schpd
  - ç¾Žå›½ 010 @schpd
  - ç¾Žå›½ 011 @schpd
  - ç¾Žå›½ 012 @schpd
  - ç¾Žå›½ 013 @schpd
  - ç¾Žå›½ 014 @schpd
  - ç¾Žå›½ 015 @schpd
  - ç¾Žå›½ 016 @schpd
  - ç¾Žå›½ 017 @schpd
  - ç¾Žå›½ 018 @schpd
  - ç¾Žå›½ 019 @schpd
  - ç¾Žå›½ 020 @schpd
  - ç¾Žå›½ 021 @schpd
  - é¦™æ¸¯ 022 @schpd
  - é¦™æ¸¯ 023 @schpd
  - é¦™æ¸¯ 024 @schpd
  - é¦™æ¸¯ 025 @schpd
rules:
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
