proxies:
- name: åŠ æ‹¿å¤§ 001 @schpd
  type: vmess
  server: c7.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: c7.620720.xyz
- name: åŠ æ‹¿å¤§ 002 @schpd
  type: vmess
  server: t1.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.620720.xyz
- name: åŠ æ‹¿å¤§ 003 @schpd
  type: vmess
  server: 7Ebc-47eA-84F0-ebcfBeF3329b.457.PP.ua
  port: 443
  uuid: 0cd3c9d1-68e5-4917-8a0a-c62f1a52de56
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 7eBc-47EA-84f0-EBCFbeF3329B.457.PP.ua
- name: åŠ æ‹¿å¤§ 004 @schpd
  type: vmess
  server: dddffgthyu.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: dDdFfGTHYU.922922.SHOP
- name: åŠ æ‹¿å¤§ 005 @schpd
  type: vmess
  server: hgtrojan.zabc.net
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /e6395c20
    headers:
      Host: hgtrojan.zabc.net
- name: åŠ æ‹¿å¤§ 006 @schpd
  type: vmess
  server: dddfhhj.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: ddDFHhj.922922.Shop
- name: åŠ æ‹¿å¤§ 007 @schpd
  type: vmess
  server: hgtrojan.zabc.net
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /e6395c20
    headers:
      Host: hgtrojan.zabc.net
- name: åŠ æ‹¿å¤§ 008 @schpd
  type: vmess
  server: DddFfRtY6.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: DddFfRtY6.922922.shop
- name: åŠ æ‹¿å¤§ 009 @schpd
  type: vmess
  server: 920a-4BCc-9A2d-57960603C7d9.457.pP.Ua
  port: 443
  uuid: a1d2e3cd-297e-4753-8e7a-6d9fb0f4aac1
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 920a-4bcc-9A2D-57960603c7d9.457.PP.ua
- name: åŠ æ‹¿å¤§ 010 @schpd
  type: vmess
  server: ddDFHhj.922922.Shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: ddDFHhj.922922.Shop
- name: åŠ æ‹¿å¤§ 011 @schpd
  type: vmess
  server: GgGgGGgGggggGg.222769.XYZ
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: gggggggggggggg.222769.xyz
- name: åŠ æ‹¿å¤§ 012 @schpd
  type: vmess
  server: 4120-Be04-13EF56096989.457.pP.Ua
  port: 443
  uuid: 0cd3c9d1-68e5-4917-8a0a-c62f1a52de56
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 4120-be04-13EF56096989.457.Pp.Ua
- name: åŠ æ‹¿å¤§ 013 @schpd
  type: vmess
  server: nnnnnnnnnnnnnn.222769.xyz
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: nnnnnnnnnnnnnn.222769.xyz
- name: åŠ æ‹¿å¤§ 014 @schpd
  type: vmess
  server: ssssssssssssfffffffgh.2032.pp.ua
  port: 443
  uuid: 4174b95d-115e-4d39-add6-1f8db95bb860
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /6We3U9Df1WGxgFnoFPw1
    headers:
      Host: ssssssssssssfffffffgh.2032.pp.ua
- name: åŠ æ‹¿å¤§ 015 @schpd
  type: vmess
  server: xxxccfrt.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: XXXccFrt.922922.ShOP
- name: åŠ æ‹¿å¤§ 016 @schpd
  type: vmess
  server: ssssssssssssfffffffgh.2032.pp.ua
  port: 443
  uuid: 4174b95d-115e-4d39-add6-1f8db95bb860
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /6We3U9Df1WGxgFnoFPw1
    headers:
      Host: ssssssssssssfffffffgh.2032.pp.ua
- name: åŠ æ‹¿å¤§ 017 @schpd
  type: vmess
  server: cCc.922922.ShOp
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: cCc.922922.ShOp
- name: åŠ æ‹¿å¤§ 018 @schpd
  type: vmess
  server: sssssssxxxx.2032.pp.ua
  port: 443
  uuid: 4174b95d-115e-4d39-add6-1f8db95bb860
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /6We3U9Df1WGxgFnoFPw1
    headers:
      Host: sssssssxxxx.2032.pp.ua
- name: åŠ æ‹¿å¤§ 019 @schpd
  type: vmess
  server: 2237-4CE3-8698-Cfd1b622333A.457.pP.uA
  port: 443
  uuid: 0cd3c9d1-68e5-4917-8a0a-c62f1a52de56
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 2237-4cE3-8698-cfd1b622333A.457.PP.UA
- name: åŠ æ‹¿å¤§ 020 @schpd
  type: vmess
  server: bbbbbbbbb.222769.xyz
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: bbbbbbbbb.222769.xyz
- name: åŠ æ‹¿å¤§ 021 @schpd
  type: vmess
  server: bBbbbbbBb.222769.XYZ
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: bbbbbbbbb.222769.xyz
- name: åŠ æ‹¿å¤§ 022 @schpd
  type: vmess
  server: NnnNNNnNnNNNNN.222769.xYZ
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: nnnnnnnnnnnnnn.222769.xyz
- name: åŠ æ‹¿å¤§ 023 @schpd
  type: vmess
  server: 51.79.102.253
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 024 @schpd
  type: vmess
  server: 104.26.8.44
  port: 80
  uuid: 5180444a-4756-43b4-960b-49eb9052e4e8
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 025 @schpd
  type: vmess
  server: t1.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.620720.xyz
- name: åŠ æ‹¿å¤§ 026 @schpd
  type: vmess
  server: 4120-bE04-13eF56096989.457.pP.UA
  port: 443
  uuid: 0cd3c9d1-68e5-4917-8a0a-c62f1a52de56
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 4120-BE04-13ef56096989.457.PP.ua
- name: åŠ æ‹¿å¤§ 027 @schpd
  type: vmess
  server: 2db-cd68-4374-9E0D-721e694FCA66.457.PP.UA
  port: 443
  uuid: 0cd3c9d1-68e5-4917-8a0a-c62f1a52de56
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 2dB-CD68-4374-9E0d-721e694fca66.457.pp.UA
- name: åŠ æ‹¿å¤§ 028 @schpd
  type: vmess
  server: vvVBgHyu.922922.SHoP
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: vvVBgHyu.922922.SHoP
- name: åŠ æ‹¿å¤§ 029 @schpd
  type: vmess
  server: sy4.620720.xyz
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sy4.620720.xyz
- name: åŠ æ‹¿å¤§ 030 @schpd
  type: vmess
  server: 104.17.18.26
  port: 80
  uuid: 5180444a-4756-43b4-960b-49eb9052e4e8
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 031 @schpd
  type: vmess
  server: hgtrojan.zabc.net
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /e6395c20
    headers:
      Host: hgtrojan.zabc.net
- name: åŠ æ‹¿å¤§ 032 @schpd
  type: vmess
  server: 4120-Be04-13EF56096989.457.pp.UA
  port: 443
  uuid: a1d2e3cd-297e-4753-8e7a-6d9fb0f4aac1
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /kT5VHYcMrphesqROzSPoHrBo
    headers:
      Host: 4120-BE04-13EF56096989.457.pp.ua
- name: åŠ æ‹¿å¤§ 033 @schpd
  type: vmess
  server: sssssssxxxx.2032.pp.ua
  port: 443
  uuid: 4174b95d-115e-4d39-add6-1f8db95bb860
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /6We3U9Df1WGxgFnoFPw1
    headers:
      Host: sssssssxxxx.2032.pp.ua
- name: åŠ æ‹¿å¤§ 034 @schpd
  type: vmess
  server: gggggggggggggg.222769.xyz
  port: 80
  uuid: 2e65577e-8fdb-4bb1-a495-96f3122099a7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /f6taOMcOSZb9TPR
    headers:
      Host: gggggggggggggg.222769.xyz
- name: åŠ æ‹¿å¤§ 035 @schpd
  type: vmess
  server: 15.235.41.200
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: ''
- name: åŠ æ‹¿å¤§ 036 @schpd
  type: vmess
  server: 104.21.75.246
  port: 80
  uuid: c458695d-6908-45c3-9512-e0c46418454c
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: å¢¨è¥¿å“¥ 037 @schpd
  type: vmess
  server: 216.238.87.47
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: none
- name: æ¾³å¤§åˆ©äºš 038 @schpd
  type: vmess
  server: support.zoom.us
  port: 8080
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /@Malinda6104
    headers:
      Host: support.zoom.us
- name: ç¾Žå›½ 039 @schpd
  type: vmess
  server: ccc.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: cCc.922922.ShOp
- name: ç¾Žå›½ 040 @schpd
  type: vmess
  server: dDdCCVFg.922922.SHOP
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: dDdCCVFg.922922.SHOP
- name: ç¾Žå›½ 041 @schpd
  type: vmess
  server: v2ray.codefyinc.com
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /vmessws
    headers:
      Host: v2ray.codefyinc.com
- name: ç¾Žå›½ 042 @schpd
  type: vmess
  server: XXXccFrt.922922.ShOP
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: XXXccFrt.922922.ShOP
- name: ç¾Žå›½ 043 @schpd
  type: vmess
  server: dddccvfg.922922.shop
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: dDdCCVFg.922922.SHOP
- name: ç¾Žå›½ 044 @schpd
  type: vmess
  server: cg1c07.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c07.waimaojd.com
- name: ç¾Žå›½ 045 @schpd
  type: vmess
  server: ZzXxdE.922922.sHOp
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: ZzXxdE.922922.sHOp
- name: ç¾Žå›½ 046 @schpd
  type: vmess
  server: cg1c04.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c04.waimaojd.com
- name: ç¾Žå›½ 047 @schpd
  type: vmess
  server: cg1c01.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c01.waimaojd.com
- name: ç¾Žå›½ 048 @schpd
  type: vmess
  server: 209.126.84.189
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /vmessws
    headers:
      Host: 209.126.84.189
- name: ç¾Žå›½ 049 @schpd
  type: vmess
  server: cg1c14.waimaojd.com
  port: 443
  uuid: be8e3136-b874-4085-bd23-ec3699300490
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /api/v1/graphql
    headers:
      Host: cg1c14.waimaojd.com
- name: ç¾Žå›½ 050 @schpd
  type: vmess
  server: dDdFfGTHYU.922922.SHOP
  port: 80
  uuid: bce0c7cb-08d1-46a7-b77b-7bff8b46252f
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /RkUUbqhA9GJZBROjL3Q5vTymr
    headers:
      Host: dDdFfGTHYU.922922.SHOP
- name: é¦™æ¸¯ 051 @schpd
  type: vmess
  server: v36.hdacd.com
  port: 30836
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 052 @schpd
  type: vmess
  server: v10.hdacd.com
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 053 @schpd
  type: vmess
  server: cgroup.node4.v.nodelist-airport.com
  port: 8312
  uuid: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 054 @schpd
  type: vmess
  server: v35.hdacd.com
  port: 30835
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  udp: true
  tls: false
  network: tcp
- name: é¦™æ¸¯ 055 @schpd
  type: vmess
  server: v10.hdacd.com
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: tcp
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - åŠ æ‹¿å¤§ 001 @schpd
  - åŠ æ‹¿å¤§ 002 @schpd
  - åŠ æ‹¿å¤§ 003 @schpd
  - åŠ æ‹¿å¤§ 004 @schpd
  - åŠ æ‹¿å¤§ 005 @schpd
  - åŠ æ‹¿å¤§ 006 @schpd
  - åŠ æ‹¿å¤§ 007 @schpd
  - åŠ æ‹¿å¤§ 008 @schpd
  - åŠ æ‹¿å¤§ 009 @schpd
  - åŠ æ‹¿å¤§ 010 @schpd
  - åŠ æ‹¿å¤§ 011 @schpd
  - åŠ æ‹¿å¤§ 012 @schpd
  - åŠ æ‹¿å¤§ 013 @schpd
  - åŠ æ‹¿å¤§ 014 @schpd
  - åŠ æ‹¿å¤§ 015 @schpd
  - åŠ æ‹¿å¤§ 016 @schpd
  - åŠ æ‹¿å¤§ 017 @schpd
  - åŠ æ‹¿å¤§ 018 @schpd
  - åŠ æ‹¿å¤§ 019 @schpd
  - åŠ æ‹¿å¤§ 020 @schpd
  - åŠ æ‹¿å¤§ 021 @schpd
  - åŠ æ‹¿å¤§ 022 @schpd
  - åŠ æ‹¿å¤§ 023 @schpd
  - åŠ æ‹¿å¤§ 024 @schpd
  - åŠ æ‹¿å¤§ 025 @schpd
  - åŠ æ‹¿å¤§ 026 @schpd
  - åŠ æ‹¿å¤§ 027 @schpd
  - åŠ æ‹¿å¤§ 028 @schpd
  - åŠ æ‹¿å¤§ 029 @schpd
  - åŠ æ‹¿å¤§ 030 @schpd
  - åŠ æ‹¿å¤§ 031 @schpd
  - åŠ æ‹¿å¤§ 032 @schpd
  - åŠ æ‹¿å¤§ 033 @schpd
  - åŠ æ‹¿å¤§ 034 @schpd
  - åŠ æ‹¿å¤§ 035 @schpd
  - åŠ æ‹¿å¤§ 036 @schpd
  - å¢¨è¥¿å“¥ 037 @schpd
  - æ¾³å¤§åˆ©äºš 038 @schpd
  - ç¾Žå›½ 039 @schpd
  - ç¾Žå›½ 040 @schpd
  - ç¾Žå›½ 041 @schpd
  - ç¾Žå›½ 042 @schpd
  - ç¾Žå›½ 043 @schpd
  - ç¾Žå›½ 044 @schpd
  - ç¾Žå›½ 045 @schpd
  - ç¾Žå›½ 046 @schpd
  - ç¾Žå›½ 047 @schpd
  - ç¾Žå›½ 048 @schpd
  - ç¾Žå›½ 049 @schpd
  - ç¾Žå›½ 050 @schpd
  - é¦™æ¸¯ 051 @schpd
  - é¦™æ¸¯ 052 @schpd
  - é¦™æ¸¯ 053 @schpd
  - é¦™æ¸¯ 054 @schpd
  - é¦™æ¸¯ 055 @schpd
rules:
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
