port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
proxies: []
proxy-groups:
- name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  proxies: []
- name: ğŸŒ ä»£ç†å·¥å…·
  type: select
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
rules:
- MATCH,ğŸŒ ä»£ç†å·¥å…·
