port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
proxies:
- name: é¦™æ¸¯ 001 @schpd_chat
  server: 8.218.238.254
  type: vmess
  port: 49496
  uuid: cb4b3605-dfcd-4100-a9a8-76df4821ee2e
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /è‹¥æƒ³èŠ‚ç‚¹å˜å˜å¥½ç”¨éœ€å…ˆæ²æµ´ç„šé¦™ç„¶åç»™qqç¾¤938399693çš„ç¾¤ä¸»ç£•800ä¸ªå“å¤´(à²¡Ï‰à²¡)
  h2-opts: {}
  delay: 749
- name: é¦™æ¸¯ 002 @schpd_chat
  server: 8.210.248.133
  type: vmess
  port: 43307
  uuid: f6a1f4ad-9d26-43c7-bce3-025df8dac591
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
  delay: 751
- name: é¦™æ¸¯ 003 @schpd_chat
  server: 8.210.248.133
  type: vmess
  port: 43425
  uuid: aa10afb0-f913-4343-9c69-bc797fcba2db
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  delay: 2937
- name: ç¾å›½ 001 @schpd_chat
  server: 154.44.14.244
  type: vmess
  port: 19724
  uuid: c393d530-034b-4df7-a90d-fb4cbc553a99
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  delay: 655
- name: ç¾å›½ 002 @schpd_chat
  type: vless
  server: nrtcfdns.zone.id
  port: 443
  uuid: 5a2c16f9-e365-4080-8d38-6924c3835586
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: snippets.kkii.eu.org
  servername: snippets.kkii.eu.org
  delay: 2321
- name: åŠ æ‹¿å¤§ 001 @schpd_chat
  type: vless
  server: 104.16.65.1
  port: 443
  uuid: 5a2c16f9-e365-4080-8d38-6924c3835586
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: snippets.kkii.eu.org
  servername: snippets.kkii.eu.org
  delay: 1823
- name: åŠ æ‹¿å¤§ 002 @schpd_chat
  type: trojan
  server: 104.19.220.22
  port: 443
  udp: true
  password: 5a2c16f9
  sni: snippets.kkii.eu.org
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: snippets.kkii.eu.org
  delay: 2370
- name: åŠ æ‹¿å¤§ 003 @schpd_chat
  type: trojan
  server: 162.159.24.131
  port: 443
  udp: true
  password: 5a2c16f9
  sni: snippets.kkii.eu.org
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: snippets.kkii.eu.org
  delay: 2434
proxy-groups:
- name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - é¦™æ¸¯ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
  - é¦™æ¸¯ 003 @schpd_chat
  - ç¾å›½ 001 @schpd_chat
  - ç¾å›½ 002 @schpd_chat
  - åŠ æ‹¿å¤§ 001 @schpd_chat
  - åŠ æ‹¿å¤§ 002 @schpd_chat
  - åŠ æ‹¿å¤§ 003 @schpd_chat
- name: ğŸŒ ä»£ç†å·¥å…·
  type: select
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
  - é¦™æ¸¯ 003 @schpd_chat
  - ç¾å›½ 001 @schpd_chat
  - ç¾å›½ 002 @schpd_chat
  - åŠ æ‹¿å¤§ 001 @schpd_chat
  - åŠ æ‹¿å¤§ 002 @schpd_chat
  - åŠ æ‹¿å¤§ 003 @schpd_chat
rules:
- MATCH,ğŸŒ ä»£ç†å·¥å…·
