port: 7890
socks-port: 7891
allow-lan: true
mode: rule
proxies:
- type: vmess
  server: 2.56.242.210
  port: 34895
  uuid: 6fe6b62a-dfbe-4753-d795-e02f2561edea
  alterId: 0
  cipher: auto
  tls: false
  network: none
  ws-opts: null
  name: åŠ æ‹¿å¤§ 001 @schpd_chat
- type: trojan
  server: 58.152.46.60
  port: 443
  password: BxceQaOe
  udp: true
  tls: false
  network: tcp
  name: é¦™æ¸¯ 002 @schpd_chat
proxy-groups:
- name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - åŠ æ‹¿å¤§ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
- name: ğŸŒ ä»£ç†å·¥å…·
  type: select
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - åŠ æ‹¿å¤§ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
rules:
- DOMAIN-SUFFIX,google.com,ğŸŒ ä»£ç†å·¥å…·
- GEOIP,CN,DIRECT
- MATCH,ğŸŒ ä»£ç†å·¥å…·
