port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
proxies:
- type: trojan
  server: 183.179.43.254
  port: 443
  password: 9bce4bead9c7407fb7e7f996d4365f85
  tls: false
  network: tcp
  name: é¦™æ¸¯ 001 @schpd_chat
proxy-groups:
- name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - é¦™æ¸¯ 001 @schpd_chat
- name: ğŸŒ ä»£ç†å·¥å…·
  type: select
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯ 001 @schpd_chat
rules:
- MATCH,ğŸŒ ä»£ç†å·¥å…·
