port: 7890
socks-port: 7891
allow-lan: true
mode: rule
proxies:
- type: vmess
  server: v12.hdacd.com
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  ws-opts: null
  name: é¦™æ¸¯ 001 @schpd_chat
- type: trojan
  server: 203.198.84.221
  port: 443
  password: BxceQaOe
  udp: true
  tls: false
  network: tcp
  name: é¦™æ¸¯ 002 @schpd_chat
- type: trojan
  server: 58.152.46.60
  port: 443
  password: BxceQaOe
  udp: true
  tls: false
  network: tcp
  name: é¦™æ¸¯ 003 @schpd_chat
proxy-groups:
- name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - é¦™æ¸¯ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
  - é¦™æ¸¯ 003 @schpd_chat
- name: ğŸŒ ä»£ç†å·¥å…·
  type: select
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯ 001 @schpd_chat
  - é¦™æ¸¯ 002 @schpd_chat
  - é¦™æ¸¯ 003 @schpd_chat
rules:
- DOMAIN-SUFFIX,google.com,ğŸŒ ä»£ç†å·¥å…·
- GEOIP,CN,DIRECT
- MATCH,ğŸŒ ä»£ç†å·¥å…·
